[build]
  functions = "functions"
  publish = "."


[[redirects]]
  from = "/api"
  to = "/.netlify/functions/captcha"
  status = 200

[[redirects]]
  from = "/hack"
  to = "https://youtu.be/dQw4w9WgXcQ?si=v9-hFSS3_IlxeTXF"
  status = 418



