[build]
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/"
  to = "/.netlify/functions/captcha"
  status = 200

[[redirects]]
  from = "/api/captcha"
  to = "/.netlify/functions/captcha"
  status = 418

[[redirects]]
  from = "/hack"
  to = "https://youtu.be/dQw4w9WgXcQ?si=v9-hFSS3_IlxeTXF"
  status = 418



